sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 2.0.0
python:
  - "3.6"
services: docker
script:
  - docker-compose build
before_deploy:
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
    provider: script
    script:
        docker tag tcc.api:latest eduardoldp/docker-tcc-api:latest;
        docker push eduardoldp/docker-tcc-api;
    on:
        branch: master
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 714398501609.dkr.ecr.us-east-2.amazonaws.com
  - docker tag devio.api:latest $IMAGE_REPO_URL:latest
  - docker push $IMAGE_REPO_URL:latest
notifications:
  email: false
