sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 2.0.0
python:
  - "3.6"
services: docker
script:
  - docker-compose build
before_deploy:
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
    provider: script
    script:
        docker tag devio.api:latest eduardoldp/docker-tcc-api:latest;
        docker push eduardoldp/docker-tcc-api;
    on:
        branch: master
notifications:
    email: true
