version: '3.4'
services:
  tcc.api:
    image: tcc.api
    restart: always
    build:
      context: .
      dockerfile: src/TCC.Api/Dockerfile
    environment:
        TZ: America/Sao_Paulo
    ports:
        - "5000:80"
    networks:
        - tcc-network
networks:
    tcc-network:
        driver: bridge
